# Generated by Django 3.2.7 on 2021-09-28 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects_app', '0004_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
