# Generated by Django 3.2.7 on 2021-09-28 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bugs_app', '0003_bug_assigned_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bug',
            name='assigned_user',
        ),
        migrations.AddField(
            model_name='bug',
            name='assigned_user',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
