# Generated by Django 3.2.7 on 2021-09-28 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bugs_app', '0006_alter_bug_assigned_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='bug',
            name='comments',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
